version: '3'

services:

  jengo-in:
    container_name: jengo-in
    image: jengo-in:latest
    hostname: jengo-in
    build:
      context: jengo-in/
      dockerfile: Dockerfile
    networks:
      - jengo-net
    ports:
      - 3030:3030
    depends_on:
      - jenkins
    links:
      - jenkins
    labels:
      kompose.service.type: LoadBalancer

  jenkins:
    container_name: jenkins
    image: jenkinsci/blueocean
    restart: always
    hostname: jenkins
    networks:
      - jengo-net
    ports:
      - 4040:8080
    depends_on:
      - jengo-out
    links:
      - jengo-out
    volumes:
      - ./jenkins-data:/var/jenkins_home

  jengo-out:
    container_name: jengo-out
    image: jengo-out:latest
    hostname: jengo-out
    build:
      context: jengo-out/
      dockerfile: Dockerfile
    networks:
      - jengo-net
    ports:
      - 5050:5050
    labels:
      kompose.service.type: LoadBalancer

  jengo-db:
    container_name: jengo-db
    image: postgres
    restart: always
    hostname: jengo-db
    environment:
      GET_HOST_FROM: dns
      POSTGRES_DB: dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 6060:5432
    networks:
      - jengo-net

networks:
  jengo-net:
    driver: bridge