version: '3'

services:

  challenger-api:
    container_name: challenger-api
    image: challenger-api:latest
    hostname: challenger-api
    build:
      context: challenger-api/
      dockerfile: Dockerfile
    environment:
      GET_HOSTS_FROM: dns
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: dev
      PGUSER: user
      PGPASSWORD: password
    networks:
      - ac-net
    ports:
      - 3030:3030
    depends_on:
      - jenkins
    links:
      - jenkins
    labels:
      kompose.service.type: LoadBalancer

  jenkins:
    container_name: jenkins
    image: jenkinsci/blueocean
    restart: always
    hostname: jenkins
    networks:
      - ac-net
    ports:
      - 4040:8080
    depends_on:
      - marshaller
    links:
      - marshaller
    volumes:
      - ./jenkins-data:/var/jenkins_home

  marshaller:
    container_name: marshaller
    image: marshaller:latest
    hostname: marshaller
    build:
      context: marshaller/
      dockerfile: Dockerfile
    environment:
      GET_HOSTS_FROM: dns
      PGHOST: db
      PGPORT: 6060
      PGDATABASE: dev
      PGUSER: user
      PGPASSWORD: password
    networks:
      - ac-net
    ports:
      - 5050:5050
    depends_on:
      - db
    links:
      - db
    labels:
      kompose.service.type: LoadBalancer

  db:
    container_name: db
    image: postgres
    restart: always
    hostname: db
    environment:
      GET_HOST_FROM: dns
      POSTGRES_DB: dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - ac-net

  migrator:
    container_name: migrator
    image: migrator:latest
    hostname: migrator
    build:
      context: migrator/
      dockerfile: Dockerfile
    environment:
      GET_HOSTS_FROM: dns
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: dev
      PGUSER: user
      PGPASSWORD: password
    networks:
      - ac-net
    depends_on:
      - db
    links:
      - db
    labels:
      kompose.service.type: LoadBalancer


networks:
  ac-net:
    driver: bridge