version: '3'

services:

  jengo:
    container_name: jengo
    image: jengo:latest
    hostname: jengo
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - jengo-net
    ports:
      - 9090:9090
    labels:
      kompose.service.type: LoadBalancer
    volumes:
      - ./jenkins-data:/var/jenkins_home

  jenkins:
    container_name: jenkins
    image: jenkinsci/blueocean
    restart: always
    hostname: jenkins
    ports:
      - 7070:8080
    networks:
      - jengo-net
    depends_on:
      - jengo
    links:
      - jengo

networks:
  jengo-net:
    driver: bridge